'use client';
import { useState, useEffect } from 'react';
import { ArrowUpRight, ArrowRight, Mountain, Heart, Hammer, Check, LockKeyhole } from 'lucide-react';
import { Progress } from '@/components/ui/progress';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const projects = [
 {name:'Bring the farmhouse back to life',short:'The farmhouse',image:'evening',tag:'01 / FIRST PRIORITY',raised:84000,goal:140000,date:'Autumn 2026',desc:'A warm kitchen, a sound roof, and a place to come home to. Help us restore the heart of the farm.',items:[['Roof timber & weatherproofing',55000],['Insulation & reclaimed windows',45000],['Kitchen materials & fittings',25000],['Contingency',15000]],steps:['Survey & clear the rooms','Repair the roof','Insulate & fit windows','Bring the kitchen to life']},
 {name:'Make room in the barn',short:'The barn',image:'mountains',tag:'02 / UP NEXT',raised:28000,goal:80000,date:'Spring 2027',desc:'From an old outbuilding to a shared space for workshops, music, and long-table dinners.',items:[['Structural timber',35000],['Flooring & repairs',25000],['Lighting & electrical work',12000],['Contingency',8000]],steps:['Clear & assess','Repair the structure','Lay the floor','Light up the space']},
 {name:'A sauna by the water',short:'The sauna',image:'river',tag:'03 / ON THE HORIZON',raised:12000,goal:60000,date:'Summer 2027',desc:'Hot stones. Cold water. A little ritual to bring us together, through every season.',items:[['Timber & cladding',25000],['Stove & chimney',18000],['Benches & insulation',11000],['Contingency',6000]],steps:['Choose the site & permissions','Build the shell','Install stove & benches','First shared sauna']}
];
const camps=[{id:'farmhouse',day:'17–18',month:'OCT',name:'A fresh start for the farmhouse',task:'Clearing, sanding & simple repairs',spots:8,total:16,date:'17–18 October 2026'}, {id:'barn',day:'24–25',month:'APR',name:'Many hands. One beautiful barn.',task:'Timber work, painting & shared meals',spots:12,total:20,date:'24–25 April 2027'}];
const money=(n:number)=>new Intl.NumberFormat('nb-NO').format(n);
export default function Home(){const [project,setProject]=useState<number|null>(null); const [donate,setDonate]=useState(false); const [amount,setAmount]=useState(500); const [camp,setCamp]=useState<number|null>(null);const [counts,setCounts]=useState<Record<string,number>>({});const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [availabilityError,setAvailabilityError]=useState(false);useEffect(()=>{fetch('/api/rsvp').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>setCounts(d as Record<string,number>)).catch(()=>setAvailabilityError(true))},[]);
useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'open_project_ledger',description:'Open a farm project budget and milestones. Does not donate.',inputSchema:{type:'object',properties:{project:{type:'string',enum:['farmhouse','barn','sauna']}},required:['project'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:unknown){const key=(input as {project?:string})?.project;const index=['farmhouse','barn','sauna'].indexOf(key||'');if(index<0)throw Error('Choose farmhouse, barn or sauna.');setProject(index);setDonate(false);return {opened:key,budget:projects[index].goal,currency:'NOK',sample:true}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return ()=>lifecycle.abort()},[]);
async function rsvp(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const form=new FormData(e.currentTarget);try{const r=await fetch('/api/rsvp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({camp:camps[camp!].id,name:form.get('name'),email:form.get('email')})});const d=await r.json() as {error?:string;count:number};if(!r.ok)throw Error(d.error);setCounts(v=>({...v,[camps[camp!].id]:d.count}));setMessage('Your preview RSVP is saved. These are sample dates; no real place is reserved.');}catch(err){setMessage(err instanceof Error?err.message:'Could not save. Please try again.');}finally{setBusy(false);}}
return <><header className="nav"><a className="brand" href="#"><Mountain size={27} strokeWidth={1.3}/>risen<span>FARM & FELLOWSHIP</span></a><nav><a href="#projects">The projects</a><a href="#dugnad">Dugnad</a><a href="#life">Life here</a></nav><div className="public-nav-actions"><a className="hub-link" href="/hub"><LockKeyhole size={15}/>Internal hub</a><a className="nav-cta" href="#projects">Be part of it <ArrowUpRight size={17}/></a></div></header>
<main><section className="hero"><img src="/images/mountains.webp" alt="Summer gathering below towering mountains"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">A MOUNTAIN FARM. A SHARED FUTURE.</p><h1>A place to gather.<br/>A place to <em>grow.</em></h1><p>We’re bringing a mountain farm to life.<br/>One project, one gathering, one pair of hands at a time.</p><a className="button light" href="#projects">Help build what’s next <ArrowDown/></a></div><span className="hero-note">ROOTED IN NATURE. BUILT TOGETHER.</span></section>
<section id="projects" className="section projects"><div className="section-head"><div><p className="eyebrow">THE NEXT CHAPTER</p><h2>Good things take a village.</h2></div><p>Choose a project. See where every krone goes.<br/>Help turn a shared idea into something real.</p></div><div className="sample">WORKING PREVIEW <span>Funding, budgets and dates below are illustrative.</span></div><div className="project-grid">{projects.map((p,i)=><article className="project" key={p.short}><button className="image-button" onClick={()=>{setProject(i);setDonate(false)}} aria-label={'Explore '+p.short}><img src={'/images/'+p.image+'.webp'} alt={i===0?'The farm gathering at dusk':i===1?'Mountain landscape and the farm campsite':'Community swimming spot among the trees'}/><span className="image-tag">{p.tag}</span><span className="image-arrow"><ArrowUpRight/></span></button><div className="project-body"><p className="meta">{p.date} <span>{Math.round(p.raised/p.goal*100)}% FUNDED</span></p><h3>{p.name}</h3><p className="description">{p.desc}</p><Progress value={p.raised/p.goal*100} aria-label={p.short+' funding progress'}/><div className="funding"><strong>{money(p.raised)} kr</strong><span>of {money(p.goal)} kr</span></div><button className="text-button" onClick={()=>{setProject(i);setDonate(false)}}>Explore the project <ArrowRight size={17}/></button></div></article>)}</div></section>
<section className="dugnad section" id="dugnad"><div className="dugnad-intro"><p className="eyebrow">GIVE YOUR TIME</p><h2>Some things are<br/>better built<br/><em>together.</em></h2><p>Dugnad is the Norwegian tradition of showing up and pitching in. Join a work weekend, learn something new, and leave a little of yourself here.</p><span className="small-line"><Hammer size={18}/> All skill levels welcome</span><span className="small-line"><Heart size={18}/> Shared meals. Fresh air. Good company.</span></div><div className="camps"><div className="camps-label">UPCOMING DUGNADS <span>SAMPLE SCHEDULE</span></div>{camps.map((c,i)=><article className="camp" key={c.id}><div className="date"><span>{c.month}</span><strong>{c.day}</strong><span>{i===0?'2026':'2027'}</span></div><div className="camp-info"><h3>{c.name}</h3><p>{c.task}</p><div className="spots"><span className="dot"/>{availabilityError?'Availability temporarily unavailable':`${Math.max(0,c.spots-(counts[c.id]||0))} of ${c.total} places available`}</div><button className="text-button" disabled={availabilityError || (counts[c.id]||0)>=c.spots} onClick={()=>{setCamp(i);setMessage('')}}>Join this dugnad <ArrowUpRight size={17}/></button></div></article>)}<p className="camp-foot">Bring your hands and your curiosity. We’ll make a plan together.</p></div></section>
<section className="section life" id="life"><div className="section-head"><div><p className="eyebrow">MORE THAN A PLACE</p><h2>This is life at Risen.</h2></div><p>A little wild. A little slower.<br/>Always better with people.</p></div><div className="life-grid"><article className="festival"><img src="/images/festival.webp" alt="Fire performance at the summer festival"/><div><p className="eyebrow">ONCE A SUMMER</p><h3>Mountains. Music. Magic.</h3><p>Our summer festival brings the farm to life.<br/>Next gathering: dates to be announced.</p></div></article><article className="quiet"><img src="/images/forest.webp" alt="Sunlight filtering through the mountain forest"/><h3>Room to just be.</h3><p>Forest walks, river dips, shared tables, and the space to find your own rhythm.</p></article></div></section>
<footer><a className="brand" href="#"><Mountain size={28}/>risen</a><p>A place we build together.</p><a href="#projects">Leave a little good behind <ArrowUpRight size={18}/></a><small>Risen farm · Working preview</small></footer></main>
<Dialog open={project!==null} onOpenChange={o=>{if(!o)setProject(null)}}><DialogContent className="project-dialog">{project!==null&&<><p className="eyebrow">{donate?'SUPPORT THE PROJECT':'THE PROJECT LEDGER'}</p><DialogTitle className="dialog-title">{projects[project].name}</DialogTitle><DialogDescription>{donate?'Donation preview — no payment is collected.':'Illustrative budget and timeline. Final costs will be confirmed before fundraising.'}</DialogDescription>{donate?<div className="donation"><label htmlFor="amount">Your contribution (NOK)</label><div className="amounts">{[250,500,1000].map(n=><button key={n} className={amount===n?'selected':''} onClick={()=>setAmount(n)}>{n} kr</button>)}</div><input id="amount" type="number" min="1" max="1000000" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><p>Your support would go toward the materials and milestones in this project’s ledger.</p><button className="button" disabled>Payments coming soon</button><p className="meta">We’re getting ready to accept donations. Nothing will be charged or added to the funding total.</p><button className="text-button" onClick={()=>setDonate(false)}>← Back to the project</button></div>:<><div className="ledger-total"><strong>{money(projects[project].raised)} kr</strong><span>of {money(projects[project].goal)} kr goal</span></div><Progress value={projects[project].raised/projects[project].goal*100} aria-label="Funding progress"/><h4>Where the money goes</h4><div className="ledger">{projects[project].items.map(([name,cost])=><div key={name}><span>{name}</span><strong>{money(Number(cost))} kr</strong></div>)}<div><strong>Total budget</strong><strong>{money(projects[project].goal)} kr</strong></div></div><h4>Milestones · {projects[project].date}</h4><ol className="milestones">{projects[project].steps.map((s,i)=><li key={s}><span>{i===0?<Check size={14}/>:i+1}</span>{s}<small>{i===0?'Complete':i===1?'Next':'Planned'}</small></li>)}</ol><button className="button" onClick={()=>setDonate(true)}>Support this project <Heart size={17}/></button></>}</>}</DialogContent></Dialog>
<Dialog open={camp!==null} onOpenChange={o=>{if(!o)setCamp(null)}}><DialogContent className="rsvp-dialog"><DialogTitle className="dialog-title">Come lend a hand.</DialogTitle><DialogDescription>{camp!==null&&camps[camp].name} · {camp!==null&&camps[camp].date}. Sample weekend — preview RSVPs only.</DialogDescription><form onSubmit={rsvp}><label htmlFor="name">Your name</label><input name="name" id="name" required maxLength={100}/><label htmlFor="email">Email address</label><input name="email" id="email" type="email" required maxLength={254}/><p className="meta">Your details are saved for this preview RSVP and are not displayed publicly.</p><button className="button" disabled={busy}>{busy?'Saving…':'Save preview RSVP'} <ArrowRight size={17}/></button><p role="status">{message}</p></form></DialogContent></Dialog></>}
function ArrowDown(){return <span aria-hidden="true">↓</span>}
