const TODAY='2026-09-08';
const projects=[
{id:'heritage',n:'01',sigil:'◇',name:'Kulturmiljø & bygningsvern',desc:'Låve, steinmur, tun, tak, konstruksjon og tradisjonelle materialer.',tags:['vern','bygg','mur']},
{id:'venue',n:'02',sigil:'⌂',name:'Låven som kulturarena',desc:'Scene, publikumsareal, brann, universell utforming, akustikk og teknisk infrastruktur.',tags:['arena','bygg','kultur']},
{id:'creative',n:'03',sigil:'∿',name:'Kreativ produksjonsarena',desc:'Studio, øving, residencies, låtskriving, produksjon og band-retreats.',tags:['studio','musikk','residency']},
{id:'festival',n:'04',sigil:'✦',name:'Festival & arrangement',desc:'Festival, konserter, jams, workshops og profesjonelt kulturprogram.',tags:['arrangement','festival']},
{id:'community',n:'05',sigil:'○',name:'Frivillighet & lokalsamfunn',desc:'Dugnad, møteplass, lokal forankring, medlemskap og åpne aktiviteter.',tags:['frivillighet','lokal']},
{id:'business',n:'06',sigil:'△',name:'Næring & reiseliv',desc:'Kommersielle retreats, studioleie, kulturturisme, overnatting og opplevelser.',tags:['næring','reiseliv']}
];
const funds=[
{id:'kmf',name:'Kulturminnefondet – faste kulturminner',owner:'Kulturminnefondet',area:['heritage'],deadline:null,cycle:'Løpende',support:'Normalt ca. 30 %',match:'Dugnad kan verdsettes til 350 kr/time',status:'Høy prioritet',url:'https://kulturminnefondet.no/sok-om-stotte/faste-kulturminner/',desc:'Restaurering og bevaring av verneverdige kulturminner. Svært relevant for gammel låve, mur og historiske konstruksjoner.',needs:['bilder','tilstandsrapport','kostnadsoverslag','finansieringsplan','eierskap','historikk'],template:'vern'},
{id:'kmfsecure',name:'Kulturminnefondet – sikringstiltak',owner:'Kulturminnefondet',area:['heritage'],deadline:null,cycle:'Løpende',support:'Prosjektavhengig',match:'Dokumenter akutt skade og risiko',status:'Vurder nå',url:'https://kulturminnefondet.no/sok-om-stotte/sikringstiltak/',desc:'For akutte tiltak som hindrer videre skade eller tap av kulturminne.',needs:['bilder','skadebeskrivelse','tilstandsrapport','kostnadsoverslag'],template:'secure'},
{id:'mrpre',name:'Forhåndsundersøkelser av verneverdige byggverk',owner:'Møre og Romsdal fylkeskommune',area:['heritage'],deadline:null,cycle:'Se utlysning',support:'Vanligvis inntil 15 000 kr; større undersøkelser kan vurderes',match:'Fylkesandel normalt maks 50 % for større tiltak',status:'Sterk match',url:'https://mrfylke.no/tenester/tilskot-prisar-og-stipend/oversikt-over-tilskot-prisar-og-stipend/tilskot-til-forehandsundersokingar-av-verneverdige-byggverk.9238.aspx',desc:'For faglig dokumentasjon før restaurering. Ordningen prioriterer blant annet gårdsbygninger og enhetslåver.',needs:['bilder','historikk','eierskap','problemstilling'],template:'prestudy'},
{id:'arena',name:'Bygg og infrastruktur – ARENA',owner:'Kulturrådet',area:['venue','creative'],deadline:'2026-09-15T13:00:00+02:00',cycle:'Årlig/utlysninger',support:'Prosjektavhengig; ikke fullfinansiering',match:'Krever realistisk finansieringsplan',status:'HASTER',url:'https://www.kulturdirektoratet.no/tilskuddsordninger/arena-tilskuddsordning-for-bygg-og-infrastruktur-tidl-rom-for-kunst',desc:'Nybygg, ombygging, oppgradering, teknisk utstyr, forprosjekt og utprøvingsprosjekt for kunst- og kulturfeltet.',needs:['prosjektbeskrivelse','budsjett','finansieringsplan','bruksplan','organisasjon','tegninger'],template:'arena'},
{id:'localvenue',name:'Spelemidlar til lokale kulturarenaer',owner:'Møre og Romsdal fylkeskommune / Rauma kommune',area:['venue'],deadline:'2027-02-15',cycle:'Årlig via kommunen',support:'Etter gjeldende retningslinjer',match:'Krever finansieringsplan og langsiktig allmenn kulturbruk',status:'Planlegg nå',url:'https://mrfylke.no/tenester/tilskot-prisar-og-stipend/oversikt-over-tilskot-prisar-og-stipend/spelemidlar-til-lokale-kulturarenaer.11283.aspx',desc:'Kan gjelde ombygging, modernisering og rehabilitering av eksisterende bygg som skal bli kulturbygg.',needs:['bruksavtale','vedtekter','driftsplan','tegninger','budsjett','finansieringsplan','universell-utforming'],template:'venue'},
{id:'kulturrom',name:'Kulturrom',owner:'Kulturrom',area:['venue','creative'],deadline:'2027-03-01',cycle:'1. mars og 1. september',support:'Ideelle søkere normalt minst 25 % egenandel',match:'Ikke planlegg med dugnad som kontant egenandel',status:'Svært relevant',url:'https://kulturrom.no/hvordan-soke/',desc:'Scene, øvingsrom, akustikk, lydisolasjon og teknisk utstyr for kulturrom.',needs:['organisasjon','bruksplan','budsjett','finansieringsplan','tilbud','akustikkplan'],template:'kulturrom'},
{id:'gjenklang',name:'Gjenklang',owner:'Kulturrom m.fl.',area:['venue','creative'],deadline:'2027-03-01',cycle:'Følg Kulturrom-utlysninger',support:'Prosjektutvikling / investeringsmodning',match:'Godt egnet før stor byggeinvestering',status:'Svært relevant',url:'https://kulturrom.no/gjenklang/sok/',desc:'Utvikling av eksisterende bygg til levende kulturarenaer – fra idé til investeringsklart prosjekt.',needs:['visjon','bruksplan','behovsanalyse','organisasjon','bilder'],template:'gjenklang'},
{id:'mrf-arr',name:'Regionalt kulturfond – arrangement, kompetanse og nettverk',owner:'Møre og Romsdal fylkeskommune',area:['festival','community','creative'],deadline:'2026-09-15T23:59:00+02:00',cycle:'15. sep 2026 / 15. jan 2027 / 1. mai 2027',support:'Prosjektavhengig',match:'Budsjett og finansieringsplan kreves',status:'HASTER',url:'https://skjema.mrfylke.no/skjema/M%C3%98R0024/Arrangement_kompetanseheving_og_nettverksbygging__Regionale_kulturfond_Mre_og_Romsdal',desc:'Arrangement, workshops, profesjonelle utøvere, kompetanseheving og nettverksbygging. Ikke bygg/vedlikehold.',needs:['prosjektbeskrivelse','budsjett','finansieringsplan','program','cv-utovere'],template:'event'},
{id:'mrdev',name:'Regionalt kulturfond – kunst- og kulturutvikling',owner:'Møre og Romsdal fylkeskommune',area:['creative','festival'],deadline:'2027-05-01',cycle:'Årlig',support:'Prosjektavhengig',match:'Utvikling, ikke ordinær drift',status:'Planlegg',url:'https://mrfylke.no/tenester/tilskot-prisar-og-stipend/oversikt-over-tilskot-prisar-og-stipend/regionale-kulturfond-kunst-og-kulturutvikling.29687.aspx',desc:'Større kunst- og kulturutvikling, produksjon, formidling og bransje-/nettverksutvikling.',needs:['prosjektbeskrivelse','budsjett','partnerskap','cv-utovere'],template:'development'},
{id:'teft',name:'TEFT-midler',owner:'Sparebanken Møre',area:['venue','community','festival','creative'],deadline:'2026-10-01',cycle:'1. april og 1. oktober',support:'Prosjektavhengig',match:'Skal ikke fullfinansiere; egeninnsats forventes',status:'Høy prioritet',url:'https://gave.sbm.no/',desc:'Allmennyttige prosjekter på Nordvestlandet innen blant annet kultur, nærmiljø og kompetanse.',needs:['organisasjon','prosjektbeskrivelse','budsjett','finansieringsplan','lokal-forankring'],template:'teft'},
{id:'smil',name:'SMIL – spesielle miljøtiltak i jordbruket',owner:'Rauma kommune / Landbruksdirektoratet',area:['heritage'],deadline:'2027-05-01',cycle:'Lokal frist må bekreftes årlig',support:'Lokale satser/prioriteringer',match:'Krever tilskuddsberettiget jordbruksproduksjon på eiendommen',status:'Avklar kvalifisering',url:'https://www.rauma.kommune.no/tjenester/naring-og-arbeid/landbruk-og-miljo/landbruk/lokale-retningslinjer-smil/',desc:'Kulturmiljø, kulturlandskap, steingjerder og enkelte verneverdige elementer i jordbruket.',needs:['jordbruksstatus','kart','bilder','kostnadsoverslag','miljoeffekt'],template:'smil'},
{id:'rauma-kultur',name:'Rauma kommune – kulturmidler',owner:'Rauma kommune',area:['festival','community'],deadline:'2027-05-01',cycle:'Årlig; bekreft dato',support:'Lokale tilskudd',match:'Tiltak må være åpne og lokalt forankret',status:'Relevant',url:'https://www.rauma.kommune.no/tjenester/kultur-fritid-og-friluftsliv/tilskudd-og-stotteordninger/kulturmidler/',desc:'Støtte til lokale lag, foreninger og kulturaktivitet.',needs:['organisasjon','prosjektbeskrivelse','budsjett','medlemmer'],template:'local'},
{id:'inno',name:'Investering i andre landbruksbaserte næringer',owner:'Innovasjon Norge',area:['business'],deadline:null,cycle:'Løpende',support:'Inntil 40 % / maks 3,5 mill. kr',match:'Hovedmålgruppe: eier av landbrukseiendom',status:'Stor mulighet',url:'https://www.innovasjonnorge.no/tjeneste/tilskudd-til-investeringer-i-andre-landbruksbaserte-naeringer',desc:'Faste anlegg og varig produksjonsutstyr for annen landbruksbasert næring, eksempelvis opplevelse/reiseliv dersom regionalt prioritert.',needs:['forretningsplan','marked','budsjett','finansieringsplan','eierskap','driftsmodell'],template:'business'},
{id:'uni',name:'Stiftelsen UNI',owner:'Stiftelsen UNI',area:['heritage'],deadline:null,cycle:'Løpende styrebehandling',support:'Prosjektavhengig',match:'Ikke samme kostnader som Ta et tak',status:'Relevant',url:'https://stiftelsen-uni.no/prosjektstotte/hva-stotter-vi',desc:'Kulturhistorisk verdifulle bygg/anlegg, sikring og skadeforebygging.',needs:['historikk','bilder','kostnadsoverslag','finansieringsplan'],template:'vern'},
{id:'taetak',name:'Ta et tak',owner:'Norsk Kulturarv',area:['heritage'],deadline:null,cycle:'Løpende/utlysning',support:'Prosjektavhengig',match:'Særlig tak på eldre bygninger',status:'Relevant',url:'https://kulturarv.no/',desc:'Bygningsvern med vekt på tak på blant annet driftsbygninger og våningshus.',needs:['bilder','historikk','takbeskrivelse','kostnadsoverslag'],template:'roof'},
{id:'gjensidige',name:'Gjensidigestiftelsen',owner:'Gjensidigestiftelsen',area:['community','festival'],deadline:null,cycle:'Utlysninger varierer',support:'Utlysningsavhengig',match:'Registrering i Frivillighetsregisteret er viktig',status:'Overvåk',url:'https://www.gjensidigestiftelsen.no/om-gjensidigestiftelsen/veiledninger/',desc:'Aktuelle utlysninger kan passe frivillighet, møteplass og aktivitet – særlig når målgruppen samsvarer med aktuell utlysning.',needs:['frivillighetsregister','organisasjon','prosjektbeskrivelse','budsjett'],template:'community'}
];
const docs=[
{id:'bilder',name:'Fotodokumentasjon',desc:'Alle fasader, skader, interiør, mur, tun og detaljbilder.'},
{id:'historikk',name:'Historikk & byggår',desc:'Byggeår, tidligere bruk, gamle bilder/kart, lokale kilder.'},
{id:'tilstandsrapport',name:'Tilstandsrapport',desc:'Faglig vurdering av konstruksjon, skader og prioriterte tiltak.'},
{id:'kostnadsoverslag',name:'Kostnadsoverslag / tilbud',desc:'Prissatte arbeider, materialer og håndverkerkostnader.'},
{id:'finansieringsplan',name:'Finansieringsplan',desc:'Egenkapital, fond, dugnad, lån, sponsorer og annen støtte.'},
{id:'budsjett',name:'Prosjektbudsjett',desc:'Utgifter og inntekter på delprosjektnivå.'},
{id:'organisasjon',name:'Organisasjonsnummer',desc:'Registrert søkerorganisasjon.'},
{id:'vedtekter',name:'Vedtekter',desc:'Formål, demokratisk struktur og disponering av midler.'},
{id:'bruksavtale',name:'Langsiktig bruksavtale',desc:'Avtale mellom privat eier og ideell forening.'},
{id:'driftsplan',name:'Driftsplan',desc:'Hvordan arenaen skal brukes, vedlikeholdes og finansieres over tid.'},
{id:'bruksplan',name:'Bruks- og aktivitetsplan',desc:'Konkrete brukere, aktiviteter, sesonger og forventet omfang.'},
{id:'tegninger',name:'Tegninger / planer',desc:'Plan, snitt, tiltakstegninger og arealbruk.'},
{id:'universell-utforming',name:'Plan for universell utforming',desc:'Tilgjengelighet for publikum, artister og frivillige.'},
{id:'akustikkplan',name:'Akustikk / lydplan',desc:'Behovsanalyse, målinger og planlagte tiltak.'},
{id:'program',name:'Program / aktivitetskalender',desc:'Artister, arrangementer, workshops og datoer.'},
{id:'cv-utovere',name:'CV-er / kunstfaglig kompetanse',desc:'Profesjonelle utøvere og samarbeidspartnere.'},
{id:'lokal-forankring',name:'Lokal forankring / intensjonsbrev',desc:'Brev fra brukere, lag, artister, kommune og samarbeidspartnere.'},
{id:'jordbruksstatus',name:'Dokumentasjon av jordbruksdrift',desc:'Produksjon, foretak/leietaker og arealstatus.'},
{id:'forretningsplan',name:'Forretningsplan',desc:'Kommersiell modell for retreat, studio, reiseliv og utleie.'},
{id:'marked',name:'Markedsgrunnlag',desc:'Målgrupper, etterspørsel, konkurrenter og betalingsvilje.'},
{id:'frivillighetsregister',name:'Frivillighetsregisteret',desc:'Dokumentasjon på registrering.'}
];
const templateLibrary={
vern:{title:'Bevaring gjennom aktiv bruk',sections:{summary:'[GÅRDSNAVN] er et historisk gårdsmiljø i Rauma som skal bevares gjennom aktiv bruk. Vi søker støtte til [TILTAK] på [BYGG/ANLEGG], med mål om å stanse forfall, ivareta opprinnelig materialbruk og sikre kulturhistoriske kvaliteter for framtiden.',need:'Tiltaket er nødvendig fordi [SKADE/TILSTAND]. Uten gjennomføring er det risiko for [KONSEKVENS].',method:'Arbeidet skal gjennomføres med [MATERIALER/METODE], i tråd med antikvariske prinsipper og faglige anbefalinger fra [RÅDGIVER].',impact:'Prosjektet sikrer kulturmiljøet samtidig som bygningen brukes aktivt til [KULTUR/FRIVILLIGHET/GÅRDSDRIFT].'}},
secure:{title:'Akutt sikring',sections:{summary:'Vi søker støtte til et avgrenset sikringstiltak på [OBJEKT] etter [STORM/SKADE].',need:'Dagens skade medfører risiko for videre tap av [KONSTRUKSJON/MUR/MATERIALE].',method:'Tiltaket avgrenses til nødvendig stabilisering og sikring: [TILTAK].',impact:'Sikringen kjøper tid og legger grunnlag for senere full restaurering.'}},
prestudy:{title:'Forhåndsundersøkelse',sections:{summary:'Vi ønsker en faglig forhåndsundersøkelse av [LÅVE/BYGG] for å etablere et dokumentert grunnlag for restaurering og aktiv bruk.',need:'Vi trenger avklaring av alder, konstruksjon, skadebilde og antikvarisk verdi før større investeringer.',method:'Undersøkelsen skal utføres av [FAGPERSON] og munne ut i tilstandsbeskrivelse, prioriteringer, materialanbefalinger og kostnadsestimat.',impact:'Rapporten skal brukes som beslutningsgrunnlag og vedlegg i senere finansierings- og byggesøknader.'}},
arena:{title:'ARENA – forprosjekt kulturarena',sections:{summary:'Vi vil utvikle en historisk gårdslåve i Rauma til en bærekraftig helårs arena for musikkproduksjon, øving, residencies, konserter og tverrfaglig kultur.',need:'Regionen mangler [BESKRIV BEHOV], samtidig som eksisterende bygningsmasse står foran nødvendig rehabilitering.',method:'Forprosjektet skal avklare arkitektur, akustikk, brann, universell utforming, teknisk infrastruktur, publikumsflyt, brukere, drift og investeringsramme.',impact:'Prosjektet kombinerer gjenbruk av eksisterende bygg med ny kulturinfrastruktur og samarbeid mellom profesjonelle og frivillige aktører.'}},
venue:{title:'Lokalt kulturbygg',sections:{summary:'Prosjektet skal transformere [LÅVEN] fra tidligere landbruksbygg til allment tilgjengelig kulturarena for Rauma og regionen.',need:'Det finnes et dokumentert behov fra [LAG/ARTISTER/BRUKERE].',method:'Tiltaket gjennomføres i faser: [BYGG], [TILGJENGELIGHET], [SCENE/AKUSTIKK], [TEKNIKK].',impact:'Arenaen får en langsiktig driftsmodell gjennom [FORENING] med [BRUKSAVTALE] og årlig aktivitetsplan.'}},
kulturrom:{title:'Kulturrom – scene/øvingsrom',sections:{summary:'Vi søker støtte til å etablere et egnet og varig kulturrom i [LÅVEN] med [AKUSTIKK/LYDISOLASJON/SCENE/UTSTYR].',need:'Dagens rom har [UTFORDRINGER] og kan ikke brukes tilfredsstillende til [AKTIVITET].',method:'Tiltakene bygger på behovsanalyse og tilbud fra [LEVERANDØR/FAGPERSON].',impact:'Investeringen vil gi bedre forhold for [BAND/ARTISTER/ARRANGØRER] og øke antall bruksdøgn fra [X] til [Y].'}},
gjenklang:{title:'Gjenklang – fra låve til levende arena',sections:{summary:'Vi ønsker å modne en historisk låve til en investeringsklar, flerfunksjonell kulturarena.',need:'Prosjektet er på idé/tidligfase og trenger profesjonell avklaring før byggeinvestering.',method:'Vi vil gjennomføre behovskartlegging, brukerdialog, konseptutvikling, tekniske undersøkelser og økonomisk/driftsmessig modellering.',impact:'Resultatet blir et robust beslutningsgrunnlag for finansiering og gjennomføring.'}},
event:{title:'Arrangement / regionalt kulturfond',sections:{summary:'[ARRANGEMENT] skal samle profesjonelle utøvere, frivillige og publikum på [GÅRDSNAVN] i Rauma.',need:'Prosjektet møter behovet for [KULTURTILBUD/MØTEPLASS/KOMPETANSE].',method:'Programmet består av [KONSERTER/WORKSHOPS/JAMS] med profesjonelle aktører honorert etter relevante bransjestandarder.',impact:'Tiltaket skaper aktivitet, nettverk og lokal/regional verdiskaping og dokumenteres gjennom publikumstall, deltakelse og evaluering.'}},
development:{title:'Kunst- og kulturutvikling',sections:{summary:'Vi vil utvikle [PROGRAM/RESIDENCY/NETTVERK] med base på gården i Rauma.',need:'Prosjektet svarer på [BEHOV] i det regionale kulturfeltet.',method:'Utviklingsløpet gjennomføres med [PARTNERE] over [PERIODE] og inkluderer [AKTIVITETER].',impact:'Resultatet skal være en varig modell for [PRODUKSJON/FORMIDLING/NETTVERK].'}},
teft:{title:'TEFT – lokal møteplass og kultur',sections:{summary:'Gjennom frivillig innsats vil vi utvikle [TILTAK] på et småbruk i Rauma til en inkluderende kultur- og møteplass.',need:'Prosjektet tar vare på eksisterende ressurser og møter et lokalt behov for [MØTEPLASS/KULTURAKTIVITET].',method:'Midlene brukes konkret til [UTSTYR/TILTAK], mens [EGENINNSATS/ANNEN FINANSIERING] dekker resten.',impact:'Prosjektet skaper varig lokal verdi gjennom [AKTIVITET], [FRIVILLIGE] og [BRUKERE].'}},
smil:{title:'SMIL – kulturmiljø',sections:{summary:'Vi søker støtte til å ivareta [STEINMUR/KULTURLANDSKAP] som del av gårdens historiske jordbruksmiljø.',need:'Elementet er skadet av [ÅRSAK] og står i fare for videre forfall.',method:'Arbeidet utføres med tradisjonell metode og tilpasses landskapet og gårdsmiljøet.',impact:'Tiltaket styrker kulturmiljø, landskapskvalitet og formidling av gårdens historie.'}},
local:{title:'Lokale kulturmidler',sections:{summary:'[FORENING] søker støtte til [AKTIVITET] på gården i Rauma.',need:'Tiltaket gir et åpent og tilgjengelig kulturtilbud lokalt.',method:'Aktiviteten gjennomføres av frivillige i samarbeid med [PARTNERE].',impact:'Vi forventer [ANTALL] deltakere og vil dokumentere aktivitet og lokal effekt.'}},
business:{title:'Landbruksbasert næringsutvikling',sections:{summary:'Vi vil utvikle en ny landbruksbasert virksomhet knyttet til [RETREAT/STUDIO/KULTURREISELIV] på gården.',need:'Konseptet utnytter eksisterende bygningsmasse og gårdens beliggenhet i Romsdalen.',method:'Investeringen omfatter [FASTE ANLEGG/UTSTYR] og bygger på dokumentert marked, prisstrategi og driftsbudsjett.',impact:'Prosjektet skal skape nye inntekter, økt bruk av gården og lokal verdiskaping.'}},
roof:{title:'Ta et tak',sections:{summary:'Vi søker støtte til å sikre og restaurere taket på [BYGG], en eldre del av gårdsmiljøet.',need:'Taket har [SKADE] og svikt vil føre til følgeskader i den historiske konstruksjonen.',method:'Arbeidet gjennomføres med [MATERIALER] og mest mulig bevaring av eksisterende konstruksjon.',impact:'Tiltaket sikrer bygningen for framtidig aktiv bruk.'}},
community:{title:'Frivillighet og møteplass',sections:{summary:'Vi vil skape en åpen møteplass for [MÅLGRUPPE] gjennom [AKTIVITET].',need:'Lokalsamfunnet har behov for [BEHOV].',method:'Prosjektet drives av frivillige med tydelige roller, samarbeidspartnere og aktivitetsplan.',impact:'Vi måler effekt gjennom deltakelse, frivilligtimer, brukerdager og videre aktivitet.'}}
};

const defaults={farm:{name:'',address:'',municipality:'Rauma',county:'Møre og Romsdal',owner:'',orgName:'',orgNo:'',sefrak:'Uavklart',agri:'Uavklart',barnYear:'',barnSize:'',vision:'Et historisk gårdsmiljø i Romsdalen skal bevares gjennom aktiv bruk og utvikles til en åpen arena for musikk, kunst, frivillighet og skapende arbeid.'},docs:{},budgets:{},applications:{},customTasks:[],ai:[]};
let state=load(); let currentView='dashboard';
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem('smabrukHub')||'{}')}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem('smabrukHub',JSON.stringify(state))}
function money(n){return new Intl.NumberFormat('nb-NO',{style:'currency',currency:'NOK',maximumFractionDigits:0}).format(Number(n)||0)}
function daysTo(d){if(!d)return null;return Math.ceil((new Date(d)-new Date(TODAY+'T00:00:00+02:00'))/86400000)}
function deadlineHTML(f){if(!f.deadline)return `<span class="badge info">${f.cycle}</span>`;let days=daysTo(f.deadline),cls=days<=7?'urgent':days<=30?'soon':'';return `<span class="deadline ${cls}">${new Date(f.deadline).toLocaleDateString('nb-NO',{day:'2-digit',month:'short',year:'numeric'})}${f.deadline.includes('T')?' · '+new Date(f.deadline).toLocaleTimeString('nb-NO',{hour:'2-digit',minute:'2-digit'}):''}</span>`}
function completeness(f){let done=f.needs.filter(x=>state.docs[x]?.done).length;return Math.round(done/f.needs.length*100)||0}
function nav(view){currentView=view;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const titles={dashboard:'Finansieringsoversikt',farm:'Gårdsprofil',projects:'Seks prosjektområder',funding:'Støtteordninger',applications:'Søknadsverksted',budgets:'Prosjektbudsjett',documents:'Dokumentbank',calendar:'Frister & handlingsplan',ai:'AI-assistent'};document.getElementById('viewTitle').textContent=titles[view];renderAlerts();render()}
function renderAlerts(){let upcoming=funds.filter(f=>f.deadline&&daysTo(f.deadline)>=0&&daysTo(f.deadline)<=30).sort((a,b)=>new Date(a.deadline)-new Date(b.deadline)).slice(0,3);document.getElementById('alertStrip').innerHTML=upcoming.map(f=>`<div class="alert"><div><strong>${f.name}</strong><br><span>${daysTo(f.deadline)} dager igjen · ${completeness(f)} % dokumentasjon klar</span></div><button class="small-btn" onclick="openFund('${f.id}')">Åpne</button></div>`).join('')}
function render(){({dashboard:renderDashboard,farm:renderFarm,projects:renderProjects,funding:renderFunding,applications:renderApplications,budgets:renderBudgets,documents:renderDocuments,calendar:renderCalendar,ai:renderAI}[currentView])()}
function renderDashboard(){let urgent=funds.filter(f=>f.deadline&&daysTo(f.deadline)>=0&&daysTo(f.deadline)<=30).length,docpct=Math.round(docs.filter(d=>state.docs[d.id]?.done).length/docs.length*100)||0;let allBudget=Object.values(state.budgets).flat().reduce((s,r)=>s+(Number(r.cost)||0),0);document.getElementById('view').innerHTML=`
<div class="grid grid-4"><div class="card metric"><div class="value">${funds.length}</div><div class="label">kartlagte støtteordninger</div><div class="delta">${funds.filter(f=>f.status.includes('HASTER')).length} haster nå</div></div><div class="card metric"><div class="value">${urgent}</div><div class="label">frister neste 30 dager</div><div class="delta">Prioriter søknader før nye tiltak</div></div><div class="card metric"><div class="value">${docpct}%</div><div class="label">masterdokumentasjon klar</div><div class="progress" style="margin-top:12px"><span style="width:${docpct}%"></span></div></div><div class="card metric"><div class="value">${money(allBudget)}</div><div class="label">registrert investeringsbehov</div><div class="delta">Fordelt på delprosjekter</div></div></div>
<div class="section-head"><div><h2>De seks finansieringssporene</h2><p>Hold kostnader og søknader separate, men bygg én samlet historie.</p></div></div>
<div class="grid grid-3">${projects.map(projectCard).join('')}</div>
<div class="section-head"><div><h2>Neste strategiske trekk</h2><p>Automatisk prioritert etter frist, relevans og dokumentasjonsgrad.</p></div></div>
<div class="table-wrap"><table><thead><tr><th>Ordning</th><th>Frist</th><th>Klarhet</th><th>Handling</th></tr></thead><tbody>${funds.filter(f=>f.deadline&&daysTo(f.deadline)>=0).sort((a,b)=>new Date(a.deadline)-new Date(b.deadline)).slice(0,8).map(f=>`<tr><td><strong>${f.name}</strong><br><span class="hint">${f.owner}</span></td><td>${deadlineHTML(f)}</td><td><div class="progress"><span style="width:${completeness(f)}%"></span></div><span class="hint">${completeness(f)} %</span></td><td><button class="small-btn" onclick="openFund('${f.id}')">Forbered</button></td></tr>`).join('')}</tbody></table></div>`}
function projectCard(p){let matching=funds.filter(f=>f.area.includes(p.id));return `<article class="card project-card"><div class="num">${p.n}</div><div class="sigil">${p.sigil}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="funding-meta"><span class="badge good">${matching.length} ordninger</span>${p.tags.map(t=>`<span class="badge">${t}</span>`).join('')}</div><button class="small-btn" onclick="openProject('${p.id}')">Åpne område</button></article>`}
function renderFarm(){let f=state.farm;document.getElementById('view').innerHTML=`<div class="grid grid-2"><div class="card"><h2>Masterprofil</h2><p class="hint">Denne informasjonen gjenbrukes i søknadsmaler og AI-assistenten.</p><form id="farmForm" class="form-grid">${field('name','Gårdsnavn',f.name)}${field('address','Sted / adresse (ikke nødvendig med full gateadresse)',f.address)}${field('municipality','Kommune',f.municipality)}${field('county','Fylke',f.county)}${field('owner','Juridisk eier',f.owner)}${field('orgName','Forening / organisasjon',f.orgName)}${field('orgNo','Organisasjonsnummer',f.orgNo)}${selectField('sefrak','SEFRAK-status',f.sefrak,['Uavklart','Ja','Nei','Delvis'])}${selectField('agri','Jordbruksproduksjon',f.agri,['Uavklart','Ja','Nei','Utleid drift'])}${field('barnYear','Omtrentlig byggeår låve',f.barnYear)}${field('barnSize','Låvens størrelse / kapasitet',f.barnSize)}<div class="field full"><label>Overordnet visjon</label><textarea name="vision">${esc(f.vision)}</textarea></div><div class="field full"><button class="primary" type="submit">Lagre gårdsprofil</button></div></form></div><div class="card"><h2>Kvalifiseringsvarsler</h2>${farmInsights().map(x=>`<div class="insight"><strong>${x.t}</strong><p>${x.p}</p></div>`).join('')}<h3 style="margin-top:24px">Juridisk anbefaling</h3><p class="hint">Privat eier beholder gården. Ideell forening får langsiktig bruksrett til definerte kulturarealer. Kommersiell drift holdes økonomisk separat.</p></div></div>`;document.getElementById('farmForm').onsubmit=e=>{e.preventDefault();state.farm=Object.fromEntries(new FormData(e.target));save();toast('Gårdsprofil lagret');render()}}
function farmInsights(){let a=[];if(!state.farm.orgNo)a.push({t:'Organisasjonsnummer mangler',p:'Flere kultur- og frivillighetsordninger krever registrert søker.'});if(state.farm.sefrak==='Uavklart')a.push({t:'Avklar SEFRAK',p:'Sjekk kommunen / kulturminnemyndighetene. Dokumentert verneverdi styrker byggesøknader.'});if(state.farm.agri==='Uavklart')a.push({t:'Avklar jordbruksstatus',p:'SMIL og landbruksbasert næringsstøtte avhenger av eiendommens drift og søker.'});if(!state.docs['bruksavtale']?.done)a.push({t:'Langsiktig bruksavtale',p:'Lag avtale mellom privat grunneier og foreningen før større kulturarena-søknader.'});return a}
function field(n,l,v){return `<div class="field"><label>${l}</label><input name="${n}" value="${esc(v||'')}"></div>`}function selectField(n,l,v,opts){return `<div class="field"><label>${l}</label><select name="${n}">${opts.map(o=>`<option ${o===v?'selected':''}>${o}</option>`).join('')}</select></div>`}
function renderProjects(){document.getElementById('view').innerHTML=`<div class="grid grid-3">${projects.map(projectCard).join('')}</div>`}
function openProject(id){let p=projects.find(x=>x.id===id),fs=funds.filter(f=>f.area.includes(id)),budget=(state.budgets[id]||[]).reduce((s,r)=>s+(+r.cost||0),0);modal(`<p class="eyebrow">${p.n} · prosjektområde</p><h2>${p.name}</h2><p>${p.desc}</p><div class="grid grid-2"><div><h3>Aktuelle ordninger</h3>${fs.map(f=>`<div class="check-row"><div><strong>${f.name}</strong><small>${f.support}</small></div></div>`).join('')}</div><div><h3>Registrert budsjett</h3><div class="budget-total">${money(budget)}</div><p class="hint">Gå til Budsjett for å detaljere tiltak.</p></div></div><button class="primary" onclick="closeModal();nav('budgets')">Åpne budsjett</button>`)}
function renderFunding(){document.getElementById('view').innerHTML=`<div class="searchbar"><input id="fundSearch" placeholder="Søk fond, formål, eier..."><select id="fundArea"><option value="">Alle områder</option>${projects.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select></div><div id="fundList" class="funding-list">${funds.map(fundRow).join('')}</div>`;document.getElementById('fundSearch').oninput=filterFunds;document.getElementById('fundArea').onchange=filterFunds}
function filterFunds(){let q=document.getElementById('fundSearch').value.toLowerCase(),a=document.getElementById('fundArea').value;document.getElementById('fundList').innerHTML=funds.filter(f=>(!a||f.area.includes(a))&&(`${f.name} ${f.owner} ${f.desc}`.toLowerCase().includes(q))).map(fundRow).join('')}
function fundRow(f){return `<article class="funding-item"><div><h3>${f.name}</h3><p>${f.desc}</p><div class="funding-meta">${f.area.map(a=>`<span class="badge">${projects.find(p=>p.id===a).name}</span>`).join('')}<span class="badge ${f.status==='HASTER'?'hot':'good'}">${f.status}</span><span class="badge info">${f.support}</span></div><div style="margin-top:8px">${deadlineHTML(f)} · <a class="source-link" href="${f.url}" target="_blank" rel="noopener">offisiell kilde ↗</a></div></div><div class="funding-actions"><button class="small-btn" onclick="openFund('${f.id}')">Detaljer</button><button class="small-btn" onclick="startApplication('${f.id}')">Lag søknad</button></div></article>`}
function openFund(id){let f=funds.find(x=>x.id===id);let pct=completeness(f);modal(`<p class="eyebrow">${f.owner}</p><h2>${f.name}</h2><p>${f.desc}</p><div class="grid grid-2"><div><h3>Finansiering</h3><p><strong>${f.support}</strong></p><p class="hint">${f.match}</p><p>${deadlineHTML(f)}</p><a class="source-link" href="${f.url}" target="_blank">Åpne offisiell kilde ↗</a></div><div><h3>Søknadsklarhet · ${pct}%</h3><div class="progress"><span style="width:${pct}%"></span></div><div class="checklist" style="margin-top:10px">${f.needs.map(id=>{let d=docs.find(x=>x.id===id);return `<label class="check-row"><input type="checkbox" ${state.docs[id]?.done?'checked':''} onchange="toggleDoc('${id}',this.checked)"><span>${d?.name||id}<small>${d?.desc||''}</small></span></label>`}).join('')}</div></div></div><button class="primary" onclick="closeModal();startApplication('${f.id}')">Åpne søknadsverksted</button>`)}
function toggleDoc(id,val){state.docs[id]={...(state.docs[id]||{}),done:val};save();renderAlerts()}
function startApplication(id){if(!state.applications[id]){let f=funds.find(x=>x.id===id),t=templateLibrary[f.template];state.applications[id]={status:'Utkast',sections:{...t.sections},notes:''};save()}closeModal();nav('applications');setTimeout(()=>selectApplication(id),0)}
function renderApplications(){let active=Object.keys(state.applications)[0]||funds[0].id;document.getElementById('view').innerHTML=`<div class="application-editor"><div><div class="toolbar-line"><strong>Søknader</strong><button class="small-btn" onclick="newApplicationModal()">+ Ny</button></div><div id="appList" class="app-list">${Object.keys(state.applications).length?Object.keys(state.applications).map(id=>appButton(id,id===active)).join(''):'<div class="empty">Ingen søknader ennå.</div>'}</div></div><div id="appEditor" class="card">${Object.keys(state.applications).length?'':'<div class="empty">Velg «Ny» eller åpne en støtteordning og trykk «Lag søknad».</div>'}</div></div>`;if(Object.keys(state.applications).length)selectApplication(active)}
function appButton(id,active=false){let f=funds.find(x=>x.id===id);return `<button class="${active?'active':''}" data-app="${id}" onclick="selectApplication('${id}')"><strong>${f.name}</strong><br><span class="hint">${state.applications[id].status} · ${completeness(f)}% dokumentasjon</span></button>`}
function selectApplication(id){let f=funds.find(x=>x.id===id),a=state.applications[id],t=templateLibrary[f.template];document.querySelectorAll('[data-app]').forEach(b=>b.classList.toggle('active',b.dataset.app===id));let editor=document.getElementById('appEditor');if(!editor)return;editor.innerHTML=`<div class="toolbar-line"><div><p class="eyebrow">${f.owner}</p><h2>${f.name}</h2></div><select id="appStatus"><option>Utkast</option><option>Under arbeid</option><option>Klar til kvalitetssikring</option><option>Sendt</option><option>Innvilget</option><option>Avslått</option></select></div><p class="hint">Mal: ${t.title}. Bytt ut tekst i [KLOMMER] med konkrete fakta. Ikke send teksten uredigert.</p>${Object.entries(a.sections).map(([k,v])=>`<div class="template-section"><h3>${sectionName(k)}</h3><textarea data-sec="${k}">${esc(v)}</textarea></div>`).join('')}<div class="template-section"><h3>Interne notater</h3><textarea data-notes>${esc(a.notes||'')}</textarea></div><div class="toolbar-line"><button class="primary" onclick="saveApplication('${id}')">Lagre utkast</button><div><button class="small-btn" onclick="copyApplication('${id}')">Kopier hele teksten</button> <button class="small-btn" onclick="askAIFor('${id}')">AI-forbedring</button></div></div>`;document.getElementById('appStatus').value=a.status}
function sectionName(k){return({summary:'Prosjektsammendrag',need:'Behov / problem',method:'Gjennomføring',impact:'Effekt / verdi'})[k]||k}
function saveApplication(id){let a=state.applications[id];document.querySelectorAll('[data-sec]').forEach(x=>a.sections[x.dataset.sec]=x.value);a.notes=document.querySelector('[data-notes]').value;a.status=document.getElementById('appStatus').value;save();toast('Søknadsutkast lagret')}
function copyApplication(id){saveApplication(id);let f=funds.find(x=>x.id===id),a=state.applications[id];navigator.clipboard?.writeText(`${f.name}\n\n`+Object.entries(a.sections).map(([k,v])=>`${sectionName(k)}\n${v}`).join('\n\n')).then(()=>toast('Søknadstekst kopiert'))}
function newApplicationModal(){modal(`<h2>Start ny søknad</h2><div class="field"><label>Velg støtteordning</label><select id="newFund">${funds.filter(f=>!state.applications[f.id]).map(f=>`<option value="${f.id}">${f.name}</option>`).join('')}</select></div><button class="primary" style="margin-top:14px" onclick="startApplication(document.getElementById('newFund').value)">Opprett</button>`)}
function renderBudgets(){let tabs=projects.map((p,i)=>`<button class="small-btn ${i===0?'active':''}" data-budget-tab="${p.id}" onclick="renderBudgetArea('${p.id}')">${p.n} ${p.name}</button>`).join('');document.getElementById('view').innerHTML=`<div class="budget-toolbar" style="flex-wrap:wrap">${tabs}</div><div id="budgetArea"></div>`;renderBudgetArea(projects[0].id)}
function renderBudgetArea(id){document.querySelectorAll('[data-budget-tab]').forEach(b=>b.classList.toggle('active',b.dataset.budgetTab===id));let rows=state.budgets[id]||[];let total=rows.reduce((s,r)=>s+(+r.cost||0),0),grant=rows.reduce((s,r)=>s+(+r.grant||0),0),dugnad=rows.reduce((s,r)=>s+(+r.hours||0)*350,0);document.getElementById('budgetArea').innerHTML=`<div class="grid grid-3"><div class="card metric"><div class="value">${money(total)}</div><div class="label">kostnader</div></div><div class="card metric"><div class="value">${money(grant)}</div><div class="label">planlagt ekstern støtte</div></div><div class="card metric"><div class="value">${money(dugnad)}</div><div class="label">dugnadsverdi @ 350 kr/t</div><div class="delta">Kun der ordningen tillater det</div></div></div><div class="section-head"><div><h2>${projects.find(p=>p.id===id).name}</h2><p>Detaljer kostnader nok til at samme post ikke søkes finansiert to ganger.</p></div><button class="primary" onclick="addBudgetRow('${id}')">+ Kostnadspost</button></div><div class="table-wrap"><table><thead><tr><th>Tiltak</th><th>Kategori</th><th>Kostnad</th><th>Dugnad t.</th><th>Planlagt fond</th><th>Støtte</th><th></th></tr></thead><tbody>${rows.length?rows.map((r,i)=>`<tr><td>${esc(r.name)}</td><td>${esc(r.category)}</td><td>${money(r.cost)}</td><td>${r.hours||0}</td><td>${esc(r.fund||'')}</td><td>${money(r.grant)}</td><td><button class="small-btn danger" onclick="deleteBudgetRow('${id}',${i})">Slett</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">Ingen kostnader registrert.</td></tr>'}</tbody></table></div>`}
function addBudgetRow(id){modal(`<h2>Ny kostnadspost</h2><form id="budgetForm" class="form-grid">${field('name','Tiltak','')}${field('category','Kategori / fag','')}${field('cost','Kostnad (NOK)','')}${field('hours','Dugnadstimer','0')}<div class="field"><label>Planlagt støtteordning</label><select name="fund"><option></option>${funds.filter(f=>f.area.includes(id)).map(f=>`<option>${f.name}</option>`).join('')}</select></div>${field('grant','Forventet støtte (NOK)','0')}<div class="field full"><button class="primary">Legg til</button></div></form>`);document.getElementById('budgetForm').onsubmit=e=>{e.preventDefault();state.budgets[id]=state.budgets[id]||[];state.budgets[id].push(Object.fromEntries(new FormData(e.target)));save();closeModal();renderBudgetArea(id)}}
function deleteBudgetRow(id,i){state.budgets[id].splice(i,1);save();renderBudgetArea(id)}
function renderDocuments(){document.getElementById('view').innerHTML=`<div class="section-head"><div><h2>Masterdokumentasjon</h2><p>Marker dokumenter klare og legg inn filnavn/notater. Selve filer lagres ikke i denne lokale versjonen.</p></div></div><div class="doc-grid">${docs.map(d=>`<div class="doc-card"><label><input type="checkbox" ${state.docs[d.id]?.done?'checked':''} onchange="toggleDoc('${d.id}',this.checked);render()"> <strong>${d.name}</strong></label><p>${d.desc}</p><input style="width:100%;padding:8px;border:1px solid var(--line);border-radius:8px" placeholder="Filnavn / lenke / notat" value="${esc(state.docs[d.id]?.note||'')}" onchange="docNote('${d.id}',this.value)"><div class="hint" style="margin-top:7px">Brukes av ${funds.filter(f=>f.needs.includes(d.id)).length} ordninger</div></div>`).join('')}</div>`}
function docNote(id,val){state.docs[id]={...(state.docs[id]||{}),note:val};save()}
function renderCalendar(){let rows=funds.filter(f=>f.deadline).sort((a,b)=>new Date(a.deadline)-new Date(b.deadline));document.getElementById('view').innerHTML=`<div class="card"><h2>Fristkalender</h2><p class="hint">Frister er forhåndsutfylt fra verifiserte 2026-kilder der tilgjengelig. Årlige 2027-datoer må alltid kontrolleres mot ny utlysning før innsending.</p><div class="timeline">${rows.map(f=>`<div class="timeline-row"><div class="date">${new Date(f.deadline).toLocaleDateString('nb-NO',{day:'2-digit',month:'short',year:'numeric'})}</div><div><h3>${f.name}</h3><p>${f.owner} · ${completeness(f)} % dokumentasjon klar</p></div><button class="small-btn" onclick="openFund('${f.id}')">Forbered</button></div>`).join('')}</div></div>`}
function renderAI(){let insights=aiInsights();document.getElementById('view').innerHTML=`<div class="ai-layout"><div class="card chat"><div class="toolbar-line"><div><h2>Støtte-Copilot</h2><p class="hint">Kjenner gårdsprofil, dokumentstatus, budsjetter, ordninger og søknadsutkast.</p></div><span class="badge ${location.protocol==='http:'||location.protocol==='https:'?'good':'warn'}">${location.protocol==='file:'?'Lokal analyse':'AI-endepunkt tilgjengelig'}</span></div><div id="messages" class="messages">${(state.ai||[]).map(m=>`<div class="bubble ${m.role==='user'?'user':'ai'}">${esc(m.text)}</div>`).join('')||'<div class="bubble ai">Jeg kan prioritere neste søknad, finne manglende vedlegg, lage prosjekttekst, kontrollere budsjettlogikk og foreslå hvilken finansieringskilde som passer en kostnad.</div>'}</div><div class="composer"><textarea id="aiPrompt" placeholder="F.eks. «Hva bør vi gjøre denne uka?» eller «Skriv et bedre ARENA-sammendrag basert på profilen vår.»"></textarea><button class="primary" onclick="sendAI()">Spør</button></div></div><div class="card"><h2>Automatisk analyse</h2>${insights.map(x=>`<div class="insight"><strong>${x.t}</strong><p>${x.p}</p></div>`).join('')}<h3 style="margin-top:20px">AI-tilkobling</h3><p class="hint">Når portalen kjøres via medfølgende <code>server.mjs</code> og miljøvariabelen <code>OPENAI_API_KEY</code> er satt på serveren, brukes /api/ai. API-nøkkel skal aldri legges i nettleserkoden.</p></div></div>`;setTimeout(()=>{let m=document.getElementById('messages');if(m)m.scrollTop=m.scrollHeight},0)}
function aiInsights(){let a=[];let urgent=funds.filter(f=>f.deadline&&daysTo(f.deadline)>=0&&daysTo(f.deadline)<=8);if(urgent.length)a.push({t:'Hastevindu',p:`${urgent.map(x=>x.name).join(' og ')} har frist innen åtte dager. Prioriter avgrenset, godt dokumentert søknad fremfor bredt byggeprosjekt.`});let missing=docs.filter(d=>!state.docs[d.id]?.done).filter(d=>funds.some(f=>f.status==='HASTER'&&f.needs.includes(d.id))).slice(0,4);if(missing.length)a.push({t:'Mangler for hasteordninger',p:missing.map(x=>x.name).join(', ')});if(!state.farm.orgNo)a.push({t:'Juridisk flaskehals',p:'Organisasjonsnummer er ikke registrert i profilen. Det begrenser flere foreningsbaserte søknader.'});if(state.farm.agri==='Uavklart')a.push({t:'SMIL / Innovasjon Norge',p:'Jordbruksstatus er uavklart. Avklar drift/eierskap før disse sporene prioriteres.'});return a}
async function sendAI(){let el=document.getElementById('aiPrompt'),q=el.value.trim();if(!q)return;state.ai=state.ai||[];state.ai.push({role:'user',text:q});el.value='';save();renderAI();let answer;try{let r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,context:compactContext()})});if(!r.ok)throw new Error('offline');let data=await r.json();answer=data.text||'Ingen tekst mottatt.'}catch(e){answer=localCopilot(q)}state.ai.push({role:'assistant',text:answer});save();renderAI()}
function localCopilot(q){q=q.toLowerCase();if(q.includes('uke')||q.includes('neste')){let f=funds.filter(x=>x.deadline&&daysTo(x.deadline)>=0).sort((a,b)=>new Date(a.deadline)-new Date(b.deadline))[0];return `Neste prioritet er ${f.name}, med frist ${new Date(f.deadline).toLocaleDateString('nb-NO')}. Dokumentasjonen er ${completeness(f)} % klar. Mangler: ${f.needs.filter(n=>!state.docs[n]?.done).map(n=>docs.find(d=>d.id===n)?.name||n).join(', ')||'ingen registrerte vedlegg'}.`};if(q.includes('mangler')||q.includes('vedlegg'))return `De mest brukte manglende dokumentene er: ${docs.filter(d=>!state.docs[d.id]?.done).sort((a,b)=>funds.filter(f=>f.needs.includes(b.id)).length-funds.filter(f=>f.needs.includes(a.id)).length).slice(0,6).map(d=>d.name).join(', ')}.`;return 'I lokal modus kan jeg prioritere frister og dokumentmangler. Kjør portalen via server.mjs med en server-side API-nøkkel for full AI-tekstbearbeiding basert på all registrert prosjektinformasjon.'}
function compactContext(){return {today:TODAY,farm:state.farm,docs:Object.fromEntries(docs.map(d=>[d.name,!!state.docs[d.id]?.done])),budgets:state.budgets,funds:funds.map(f=>({name:f.name,deadline:f.deadline,support:f.support,desc:f.desc,needs:f.needs,areas:f.area})),applications:state.applications}}
function askAIFor(id){saveApplication(id);nav('ai');setTimeout(()=>{document.getElementById('aiPrompt').value=`Forbedre søknadsutkastet til ${funds.find(f=>f.id===id).name}. Behold fakta, marker tydelig hvilke opplysninger som fortsatt mangler, og gjør teksten konkret mot ordningens formål.`},0)}
function modal(html){document.getElementById('modalBody').innerHTML=html;document.getElementById('modal').classList.remove('hidden')}function closeModal(){document.getElementById('modal').classList.add('hidden')}function toast(t){let x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function exportData(){let blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='smabruk-stottehub-data.json';a.click();URL.revokeObjectURL(a.href)}
function quickAdd(){modal(`<h2>Nytt tiltak / oppgave</h2><form id="taskForm" class="form-grid">${field('name','Navn','')}${field('due','Frist','')}<div class="field full"><label>Prosjektområde</label><select name="area">${projects.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select></div><div class="field full"><button class="primary">Legg til</button></div></form>`);document.getElementById('taskForm').onsubmit=e=>{e.preventDefault();state.customTasks.push(Object.fromEntries(new FormData(e.target)));save();closeModal();toast('Tiltak lagt til')}}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>nav(b.dataset.view));document.getElementById('modalClose').onclick=closeModal;document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.getElementById('exportBtn').onclick=exportData;document.getElementById('quickAddBtn').onclick=quickAdd;document.getElementById('importInput').onchange=e=>{let file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);state=d.state||d;save();toast('Data importert');render()}catch{alert('Kunne ikke lese filen')}};r.readAsText(file)};
window.nav=nav;window.openProject=openProject;window.openFund=openFund;window.closeModal=closeModal;window.toggleDoc=toggleDoc;window.startApplication=startApplication;window.selectApplication=selectApplication;window.newApplicationModal=newApplicationModal;window.saveApplication=saveApplication;window.copyApplication=copyApplication;window.askAIFor=askAIFor;window.renderBudgetArea=renderBudgetArea;window.addBudgetRow=addBudgetRow;window.deleteBudgetRow=deleteBudgetRow;window.docNote=docNote;window.sendAI=sendAI;
renderAlerts();render();
