/**
 * Builds the seed INSERT statements from `data/risen.ts`.
 *
 * Shared by the local bootstrap, the remote migration script and the
 * `drizzle/seed.sql` generator, so there is exactly one definition of the seed
 * and the three cannot drift.
 *
 * Run directly to regenerate the checked-in file:
 *   node scripts/seed-sql.mjs
 */
import { writeFileSync } from 'node:fs';

const quote = value => {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return String(value);
  return `'${String(value).replaceAll("'", "''")}'`;
};

const insert = (table, columns, rows) =>
  rows
    .map(
      row =>
        `INSERT OR IGNORE INTO ${table} (${columns.join(', ')}) VALUES (${columns
          .map(column => quote(row[column]))
          .join(', ')});`,
    )
    .join('\n');

export async function buildSeedSql(timestamp = new Date().toISOString()) {
  const { seedPlaces, seedProjects, seedMilestones, seedWorkItems } = await import('../data/risen.ts');
  const stamped = rows => rows.map(row => ({ ...row, created_at: timestamp, updated_at: timestamp }));

  return [
    insert(
      'places',
      ['id', 'slug', 'name', 'kind', 'summary', 'condition', 'visibility', 'created_at', 'updated_at'],
      stamped(seedPlaces),
    ),
    insert(
      'projects',
      ['id', 'slug', 'name', 'summary', 'category', 'status', 'progress', 'budget_nok', 'funded_nok', 'next_action', 'place_id', 'visibility', 'published_at', 'created_at', 'updated_at'],
      stamped(seedProjects).map(project => ({
        ...project,
        budget_nok: project.budgetNok,
        funded_nok: project.fundedNok,
        next_action: project.nextAction,
        place_id: project.placeId,
        published_at: project.publishedAt,
      })),
    ),
    insert(
      'milestones',
      ['id', 'project_id', 'title', 'detail', 'status', 'position', 'due_date', 'completed_at', 'visibility', 'created_at', 'updated_at'],
      stamped(seedMilestones).map(milestone => ({
        ...milestone,
        project_id: milestone.projectId,
        due_date: milestone.dueDate,
        completed_at: milestone.completedAt,
      })),
    ),
    insert(
      'work_items',
      ['id', 'project_id', 'place_id', 'milestone_id', 'title', 'detail', 'type', 'priority', 'status', 'assignee', 'due_date', 'visibility', 'created_at', 'updated_at'],
      stamped(seedWorkItems).map(item => ({
        ...item,
        project_id: item.projectId,
        place_id: item.placeId,
        milestone_id: item.milestoneId,
        due_date: item.dueDate,
      })),
    ),
  ].join('\n\n');
}

const isDirectRun = import.meta.url === `file://${process.argv[1]}`;
if (isDirectRun) {
  const header = [
    '-- Generated by `npm run db:seed-sql` from data/risen.ts. Do not edit by hand.',
    '--',
    '-- Demo records for an empty Risen database. Safe to run more than once:',
    '-- every statement is INSERT OR IGNORE. Run the migrations in this folder first.',
    '--',
    '-- All figures are illustrative. Nothing here is a verified cost or deadline.',
    '',
  ].join('\n');
  writeFileSync('drizzle/seed.sql', `${header}${await buildSeedSql('2026-09-20T00:00:00.000Z')}\n`, 'utf8');
  console.log('Wrote drizzle/seed.sql');
}
